import { Colors, Fonts } from "./generalStyles";
import { StyleSheet } from "react-native";

export const createWalkStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: Colors.white,
    marginTop: "5%",
  },

  title: {
    fontFamily: Fonts.montserrat,
    fontSize: 28,
    fontWeight: "700",
    lineHeight: 35,
    color: Colors.neutral,
    marginBottom: "5%",
  },
  label: {
    fontSize: 18,
    marginBottom: "5%",
  },
  buttonContainer: {
    flexDirection: "column",
    alignItems: "center",
  },
  buttonLarge: {
    marginBottom: "5%",
    width: "100%",
    height: 52,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: Fonts.montserrat,
    fontSize: 18,
    fontWeight: "400",
    lineHeight: 28,
    backgroundColor: Colors.gray5,
    borderRadius: 8,
  },
  buttonLargeEnd: {
    marginBottom: "5%",
    width: "100%",
    height: 52,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: Fonts.montserrat,
    fontSize: 18,
    fontWeight: "400",
    lineHeight: 28,
    backgroundColor: Colors.orange,
    borderRadius: 8,
  },
  buttonShort: {
    marginBottom: "5%",
    marginLeft: "5%",
    width: "35%",
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    fontFamily: Fonts.montserrat,
    fontSize: 18,
    fontWeight: "400",
    lineHeight: 28,
    backgroundColor: Colors.gray5,
    borderRadius: 8,
  },
  buttonText: {
    fontFamily: Fonts.montserrat,
    fontSize: 18,
    fontWeight: "400",
    lineHeight: 28,
    color: Colors.orange,
  },
  buttonTextEnd: {
    fontFamily: Fonts.montserrat,
    fontSize: 18,
    fontWeight: "400",
    lineHeight: 28,
    color: Colors.white,
  },
  immediateContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  picker: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 4,
    padding: 8,
    marginBottom: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 4,
    padding: 8,
    marginBottom: 16,
    height: 100,
  },
});
export default createWalkStyles;
